name: Build Android APK (Flutter)

on:
  push:
    tags:
      - 'v*'                 # يبني تلقائيًا عند إنشاء Tag مثل v0.2
  workflow_dispatch:         # لتشغيله يدويًا من تبويب Actions

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Flutter pub get
        run: flutter pub get

      # نسخة قابلة للتثبيت مباشرة (Debug)
      - name: Build DEBUG APK (signed with debug key)
        run: flutter build apk --debug

      # نسخة إصدار (Release)
      - name: Build RELEASE APK
        run: flutter build apk --release

      # رفع الملفين كـ Artifacts دائمًا
      - name: Upload APK artifacts
        uses: actions/upload-artifact@v4
        with:
          name: apks
          path: |
            build/app/outputs/flutter-apk/app-debug.apk
            build/app/outputs/flutter-apk/app-release.apk

      # عند وجود Tag (مثلاً v0.2) أنشئ Release وارفع الـ APKs
      - name: Create GitHub Release and upload APKs
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          files: |
            build/app/outputs/flutter-apk/app-debug.apk
            build/app/outputs/flutter-apk/app-release.apk
update workflow
